apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: argocd-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: imac.fritz.box:5000/disposab1e/argocd-operator-helm-registry-ocp:0.0.4
  displayName: Argo CD Operators
  publisher: Argo CD
