#!/usr/bin/env bash

set -e

# operator-courier
echo "Installing operator-courier"
python3 -m pip install operator-courier

# Operator SDK
echo "Installing operator-sdk"
OPERATOR_SDK_VER=v0.15.0
curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VER}/operator-sdk-${OPERATOR_SDK_VER}-x86_64-linux-gnu
chmod +x operator-sdk
sudo mv operator-sdk /usr/local/bin/

# Helm
echo "Installing helm-3"
curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

# kubectl
echo "Installing kubectl"
KUBECTL_VERSION="v1.14.0"
curl -Lo kubectl "https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
chmod +x kubectl
sudo mv kubectl /usr/local/bin/

# Minikube
echo "Installing minikube"
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
chmod +x minikube
sudo mv minikube /usr/local/bin/
